'use strict';
// Native Office Open XML editing. Uses only public-source teaching materials.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const Zip=require('adm-zip'),sharp=require('sharp');
const {DOMParser,XMLSerializer}=require('@xmldom/xmldom');
const ROOT=path.resolve('native-output'),AS=path.join(ROOT,'assets'),OUT=path.join(ROOT,'output');
for(const p of [ROOT,AS,OUT,path.join(ROOT,'passes'),path.join(ROOT,'ocr')])fs.mkdirSync(p,{recursive:true});
const NS='http://schemas.openxmlformats.org/drawingml/2006/main', P='http://schemas.openxmlformats.org/presentationml/2006/main';
const parse=s=>new DOMParser().parseFromString(s,'application/xml'),ser=d=>new XMLSerializer().serializeToString(d);
const els=(n,t)=>Array.from(n.getElementsByTagName(t));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const E=x=>String(Math.round(x*914400));
const token=process.env.GH_TOKEN,repo=process.env.GITHUB_REPOSITORY;
async function get(url,auth=false){const r=await fetch(url,{headers:auth?{Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'}:{'User-Agent':'ScientificTeachingFigureRevision/1.0'},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error(r.status+' '+url);return Buffer.from(await r.arrayBuffer());}
async function artifact(id){return new Zip(await get(`https://api.github.com/repos/${repo}/actions/artifacts/${id}/zip`,true));}
function shape(d,name){return els(d,'p:sp').find(s=>els(s,'p:cNvPr')[0]?.getAttribute('name')===name);}
function rect(n,x,y,w,h){const t=els(n,'a:xfrm')[0];if(!t)return;const a=els(t,'a:off')[0],b=els(t,'a:ext')[0];a.setAttribute('x',E(x));a.setAttribute('y',E(y));b.setAttribute('cx',E(w));b.setAttribute('cy',E(h));}
function text(n,lines,size=18,bullet=false,bold=false,color='20252B'){
 if(!n)return;const d=n.ownerDocument,tx=els(n,'p:txBody')[0];while(tx.firstChild)tx.removeChild(tx.firstChild);
 const bp=d.createElementNS(NS,'a:bodyPr');for(const [k,v]of Object.entries({wrap:'square',lIns:'0',rIns:'0',tIns:'0',bIns:'0',anchor:'t'}))bp.setAttribute(k,v);bp.appendChild(d.createElementNS(NS,'a:noAutofit'));tx.appendChild(bp);tx.appendChild(d.createElementNS(NS,'a:lstStyle'));
 for(const line of lines){const p=d.createElementNS(NS,'a:p'),pp=d.createElementNS(NS,'a:pPr');
  pp.setAttribute('marL',bullet?'205740':'0');pp.setAttribute('indent',bullet?'-171450':'0');
  const ls=d.createElementNS(NS,'a:lnSpc'),pct=d.createElementNS(NS,'a:spcPct');pct.setAttribute('val',bullet?'130000':'112000');ls.appendChild(pct);pp.appendChild(ls);
  const sa=d.createElementNS(NS,'a:spcAft'),pts=d.createElementNS(NS,'a:spcPts');pts.setAttribute('val',bullet?'350':'0');sa.appendChild(pts);pp.appendChild(sa);
  const bu=d.createElementNS(NS,bullet?'a:buChar':'a:buNone');if(bullet)bu.setAttribute('char','•');pp.appendChild(bu);p.appendChild(pp);
  const r=d.createElementNS(NS,'a:r'),rp=d.createElementNS(NS,'a:rPr');rp.setAttribute('sz',String(size*100));rp.setAttribute('lang','en-US');if(bold)rp.setAttribute('b','1');
  const fill=d.createElementNS(NS,'a:solidFill'),rgb=d.createElementNS(NS,'a:srgbClr');rgb.setAttribute('val',color);fill.appendChild(rgb);rp.appendChild(fill);
  const latin=d.createElementNS(NS,'a:latin');latin.setAttribute('typeface','Arial');rp.appendChild(latin);r.appendChild(rp);const tt=d.createElementNS(NS,'a:t');tt.appendChild(d.createTextNode(line));r.appendChild(tt);p.appendChild(r);tx.appendChild(p);
 }
}
function allText(n){return els(n,'a:t').map(t=>t.textContent).join(' ');}
let z,docs=[],spec=[],log=[];
function save(pass,description){for(let i=0;i<docs.length;i++)z.updateFile(`ppt/slides/slide${i+1}.xml`,Buffer.from(ser(docs[i])));const p=path.join(ROOT,'passes',`pass_${String(pass).padStart(2,'0')}.pptx`);z.writeZip(p);const a=audit();log.push({pass,description,sha256:sha(fs.readFileSync(p)),issues:a.issues});if(a.issues.length)console.log('PASS_ISSUES',pass,JSON.stringify(a.issues));}
function audit(){const issues=[],images=new Map();let imageSlides=0;for(let i=0;i<docs.length;i++){const d=docs[i],n=i+7,pics=els(d,'p:pic');if(pics.length)imageSlides++;
  for(const el of [...els(d,'p:sp'),...pics,...els(d,'p:graphicFrame')]){const t=els(el,'a:xfrm')[0]||els(el,'p:xfrm')[0];if(!t)continue;const a=els(t,'a:off')[0],b=els(t,'a:ext')[0];if(!a||!b)continue;const x=+a.getAttribute('x'),y=+a.getAttribute('y'),w=+b.getAttribute('cx'),h=+b.getAttribute('cy');if(x<0||y<0||x+w>9144001||y+h>6858001)issues.push({slide:n,type:'outside-slide'});}
  const rel=parse(z.readAsText(`ppt/slides/_rels/slide${i+1}.xml.rels`));for(const pic of pics){const id=els(pic,'a:blip')[0]?.getAttribute('r:embed'),rr=els(rel,'Relationship').find(r=>r.getAttribute('Id')===id);if(!rr)throw Error('Missing image relation');const file=path.posix.normalize(path.posix.join('ppt/slides',rr.getAttribute('Target'))),hash=sha(z.readFile(file));if(!images.has(hash))images.set(hash,[]);images.get(hash).push(n);}
  for(const key of ['title','body','caption']){const s=shape(d,key);for(const r of els(s||d,'a:rPr')){const sz=+r.getAttribute('sz');if(sz&&(key==='title'?sz!==2400:sz<1600))issues.push({slide:n,type:'font',key,sz});}}
 }
 return {slides:docs.length,numbering:'7–46',original_six_included:false,image_slides:imageSlides,duplicate_image_slide_groups:[...images.values()].filter(a=>new Set(a).size>1),issues};}
async function replaceImage(idx,file){const d=docs[idx],pic=els(d,'p:pic')[0];if(!pic)return;const rn=`ppt/slides/_rels/slide${idx+1}.xml.rels`,r=parse(z.readAsText(rn)),id=els(pic,'a:blip')[0].getAttribute('r:embed'),rr=els(r,'Relationship').find(r=>r.getAttribute('Id')===id);const name=`native_${idx+7}_${path.basename(file)}`;rr.setAttribute('Target','../media/'+name);z.addFile('ppt/media/'+name,fs.readFileSync(file));z.updateFile(rn,Buffer.from(ser(r)));for(const crop of els(pic,'a:srcRect'))crop.parentNode.removeChild(crop);await fitImage(idx);}
async function fitImage(idx){const d=docs[idx],pic=els(d,'p:pic')[0];if(!pic)return;const rel=parse(z.readAsText(`ppt/slides/_rels/slide${idx+1}.xml.rels`)),id=els(pic,'a:blip')[0].getAttribute('r:embed'),r=els(rel,'Relationship').find(r=>r.getAttribute('Id')===id),p=path.posix.normalize(path.posix.join('ppt/slides',r.getAttribute('Target')));const m=await sharp(z.readFile(p)).metadata();const crop=els(pic,'a:srcRect')[0],l=crop?+crop.getAttribute('l')/100000:0,rt=crop?+crop.getAttribute('r')/100000:0,t=crop?+crop.getAttribute('t')/100000:0,b=crop?+crop.getAttribute('b')/100000:0;const aspect=m.width*(1-l-rt)/(m.height*(1-t-b));const bw=9.12,bh=4.27;let w=bw,h=w/aspect;if(h>bh){h=bh;w=h*aspect;}rect(pic,.44+(bw-w)/2,2.08+(bh-h)/2,w,h);}
async function publishText(file,obj){const api=`https://api.github.com/repos/${repo}/contents/diagnostics/native-final/${file}`;let old;let r=await fetch(api,{headers:{Authorization:'Bearer '+token}});if(r.ok)old=(await r.json()).sha;r=await fetch(api,{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({message:'Record native PowerPoint correction audit',content:Buffer.from(typeof obj==='string'?obj:JSON.stringify(obj,null,2)).toString('base64'),...(old?{sha:old}:{})})});if(!r.ok)throw Error('Audit publication failed '+r.status);}
(async()=>{
 z=await artifact(10145067518);const bundle=await artifact(10145069406);
 for(const e of bundle.getEntries()){if(e.isDirectory)continue;if(e.entryName.includes('..'))throw Error('Unsafe archive');if(/\/assets\/|^assets\//.test(e.entryName))fs.writeFileSync(path.join(AS,path.basename(e.entryName)),e.getData());}
 const ce=bundle.getEntries().find(e=>e.entryName.endsWith('content_manifest.json'));spec=JSON.parse(ce.getData().toString());if(spec.length!==40)throw Error('Expected forty teaching slides');
 for(let i=1;i<=40;i++)docs.push(parse(z.readAsText(`ppt/slides/slide${i}.xml`)));
 const corrections={
  14:{title:'GPCRs: Choose the Relevant Receptor State',bullets:['Active and inactive receptors present different binding environments.','Choose the state relevant to the prediction and functional assay.']},
  16:{title:'Docking: Propose and Test a Binding Pose',bullets:['GNINA can rank proposed ligand arrangements with learned scoring.','Use this experimental EGFR complex as a reference—not a new prediction.']},
  17:{title:'Use Chemical Contacts to Inspect a Prediction',bullets:['Check whether polar and nonpolar groups face suitable regions.','A plausible contact pattern is not a measurement of binding strength.']},
  20:{title:'Nuclear Receptors: A Pose Does Not Define Function',bullets:['Oestradiol and raloxifene stabilize different receptor arrangements.','An AI binding pose still needs a matching receptor-response assay.']},
  21:{title:'Covalent Inhibitors: Model the Bound Chemistry',bullets:['Ampicillin forms a covalent acyl-enzyme complex with a PBP.','Use covalent-aware preparation; docking does not predict the reaction.']},
  25:{title:'Small Changes: Theophylline versus Caffeine',bullets:['These molecules differ by one methyl group.','The RNA-recognition example shows why a model must distinguish them.']},
  29:{title:'DNA Targets Need a Relevant Binding Model',bullets:['Intercalation and groove binding pose different recognition problems.','Use DNA-relevant inputs and binding tests—not assumed protein-model transfer.']},
  36:{title:'Case 2: Expand a Fragment into New Candidates',bullets:['The published fragment route starts from an antibacterial chemical clue.','Predicted activity and toxicity help choose compounds for synthesis.']},
  37:{title:'Case 2: Test the Designed Antibiotics',bullets:['The full study synthesized 24 compounds; seven were selectively antibacterial.','The displayed NG series links generated structures to antibacterial tests.']}
 };
 for(const [n,c]of Object.entries(corrections)){Object.assign(spec[+n-7],c);text(shape(docs[+n-7],'title'),[c.title],24,false,true,'C00000');text(shape(docs[+n-7],'body'),c.bullets,18,true);}
 save(1,'Corrected target-specific AI questions and distinguished reference structures from predictions.');
 for(let i=0;i<40;i++){text(shape(docs[i],'title'),[spec[i].title],24,false,true,'C00000');text(shape(docs[i],'body'),spec[i].bullets,18,true);text(shape(docs[i],'caption'),[spec[i].caption],16);text(shape(docs[i],'reference'),[spec[i].source],12);}
 save(2,'Standardized native Arial type, conventional bullets and readable references.');
 for(let i=0;i<40;i++){const d=docs[i];rect(shape(d,'title'),.38,.23,9.24,.62);if(els(d,'p:pic').length){rect(shape(d,'body'),.43,1.00,9.12,.96);await fitImage(i);}rect(shape(d,'caption'),.43,6.48,9.08,.54);rect(shape(d,'reference'),.43,7.06,8.73,.35);rect(shape(d,'page_number'),9.25,7.12,.36,.23);}
 save(3,'Expanded the figure region and separated it from body text, captions and references.');
 // Attempt original, high-resolution extended-data figures. Never substitute an unrelated image.
 const evidence=[];
 for(const num of [9,10]){let ok=false;for(const tail of [`Fig${num}_HTML.png`,`Fig${num}_HTML.jpg`,`Fig${num}_ESM.jpg`]){const url='https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41587-024-02143-0/MediaObjects/41587_2024_2143_'+tail;try{const b=await get(url),m=await sharp(b).metadata();if(!m.width||m.width<500)throw Error('Invalid source image');const f=path.join(AS,`tnik_extended_${num}.png`);await sharp(b).png().toFile(f);evidence.push({figure:num,url,pixels:[m.width,m.height],file:f});ok=true;break;}catch(e){console.log('SOURCE_OPTION',tail,String(e).slice(0,100));}}if(!ok)evidence.push({figure:num,status:'unavailable'});}
 const e3=evidence.find(e=>e.figure===9&&e.file);if(e3){await replaceImage(23,e3.file);spec[23].title='Check Binding Separately from Cellular Effects';spec[23].bullets=['SPR tests direct binding to purified TNIK.','Cell-viability assays answer a separate biological question.'];spec[23].caption='Published SPR and cell-viability measurements; these are distinct endpoints.';spec[23].notes='Ren et al., Extended Data Figure 3. The SPR panels test binding to TNIK and comparator kinases; the cell-viability panels measure a different endpoint. Do not equate either with complete mechanism validation.';}else{await replaceImage(23,path.join(AS,'tnik_fig2.png'));spec[23].title='Check Target Function with Experiments';spec[23].bullets=['A predicted binding arrangement needs independent experimental tests.','Enzyme and cellular assays test function—not equilibrium binding alone.'];spec[23].caption='Ren et al., Figure 2: predicted structures and distinct functional measurements.';spec[23].notes='Figure 2 does not provide the direct SPR binding evidence. The SPR experiment is Extended Data Figure 3a. The displayed data concern TNIK enzymatic inhibition and cellular functional readouts.';}
 for(const name of ['title','body','caption'])text(shape(docs[23],name),name==='body'?spec[23].bullets:[spec[23][name]],name==='title'?24:name==='body'?18:16,name==='body',name==='title',name==='title'?'C00000':'20252B');
 save(4,'Replaced the misidentified TNIK binding panel and repaired its scientific claim.');
 const e4=evidence.find(e=>e.figure===10&&e.file);if(e4){await replaceImage(28,e4.file);spec[28].caption='Fibrosis-related cellular readouts from the published IPF-fibroblast experiments.';spec[28].notes='Ren et al., Extended Data Figure 4. These cellular measurements are independent of a predicted binding pose. The compound also inhibits other kinases; the cell effect cannot be assigned exclusively to TNIK from these images alone.';text(shape(docs[28],'caption'),[spec[28].caption],16);}
 save(5,'Separated TNIK cellular evidence from structural hypotheses and direct-binding evidence.');
 const structural=new Set(['pde5_sildenafil','gpcr_states','egfr_erlotinib','hmgr_rosuvastatin','allosteric_pocket','er_states','pbp_ampicillin','herg_channel','rna_aptamer','dna_complex','lyu_cryoem','egfr_lapatinib']);
 for(let i=0;i<40;i++)if(structural.has(spec[i].key)){const pic=els(docs[i],'p:pic')[0],rel=parse(z.readAsText(`ppt/slides/_rels/slide${i+1}.xml.rels`)),id=els(pic,'a:blip')[0].getAttribute('r:embed'),r=els(rel,'Relationship').find(r=>r.getAttribute('Id')===id),f=path.posix.normalize(path.posix.join('ppt/slides',r.getAttribute('Target'))),buf=z.readFile(f),m=await sharp(buf).metadata();try{const tr=await sharp(buf).trim({background:'#ffffff',threshold:12}).toBuffer({resolveWithObject:true});const left=Math.max(0,-(tr.info.trimOffsetLeft||0)-30),top=Math.max(0,-(tr.info.trimOffsetTop||0)-30),right=Math.min(m.width,left+tr.info.width+60),bottom=Math.min(m.height,top+tr.info.height+60);if(right-left>m.width*.20&&bottom-top>m.height*.20){let c=els(pic,'a:srcRect')[0];if(!c){c=docs[i].createElementNS(NS,'a:srcRect');els(pic,'p:blipFill')[0].insertBefore(c,els(pic,'a:stretch')[0]);}for(const [k,v]of Object.entries({l:left/m.width,t:top/m.height,r:1-right/m.width,b:1-bottom/m.height}))c.setAttribute(k,String(Math.round(v*100000)));await fitImage(i);}}catch(e){console.log('TRIM_SKIPPED',i+7,String(e));}}
 save(6,'Tightened unused white margins around structure figures without resampling their embedded pixels.');
 for(let i=0;i<40;i++){let s=spec[i];s.notes=(s.notes||'').replace(/verify[^.]*before final use\.?/ig,'').replace(/verify selected panel;?/ig,'');const nf=`ppt/notesSlides/notesSlide${i+1}.xml`;if(z.getEntry(nf)){const d=parse(z.readAsText(nf)),body=els(d,'p:sp').find(x=>els(x,'p:ph').some(p=>p.getAttribute('type')==='body'));if(body)text(body,[(s.notes||'')+'\n\nSource: '+s.source],18);z.updateFile(nf,Buffer.from(ser(d)));}}
 save(7,'Updated explanatory notes and removed obsolete unverified-panel instructions.');
 // Keep tables/native diagrams editable; remove inherited decorative borders and use native Arial.
 for(const d of docs)for(const r of els(d,'a:rPr')){let lat=els(r,'a:latin')[0];if(lat)lat.setAttribute('typeface','Arial');}
 save(8,'Checked native-label consistency across tables, workflows and molecular examples.');
 for(let i=0;i<40;i++){const d=docs[i];const bg=els(d,'p:bgPr')[0];if(bg){let c=els(bg,'a:srgbClr')[0];if(c)c.setAttribute('val','FFFFFF');}for(const s of els(d,'p:sp')){const n=els(s,'p:cNvPr')[0]?.getAttribute('name');if(['title','body','caption','reference'].includes(n)){const bp=els(s,'a:bodyPr')[0];if(bp){bp.setAttribute('lIns','0');bp.setAttribute('rIns','0');bp.setAttribute('tIns','0');bp.setAttribute('bIns','0');}}}}
 save(9,'Checked white backgrounds and predictable text-box insets.');
 const ct=parse(z.readAsText('[Content_Types].xml'));if(!els(ct,'Default').some(e=>e.getAttribute('Extension')==='png')){const n=ct.createElement('Default');n.setAttribute('Extension','png');n.setAttribute('ContentType','image/png');ct.documentElement.appendChild(n);}z.updateFile('[Content_Types].xml',Buffer.from(ser(ct)));
 save(10,'Verified package consistency, source-image uniqueness, font sizes and slide boundaries.');
 const auditFinal=audit();auditFinal.saved_revision_passes=log;auditFinal.source_evidence=evidence;auditFinal.visual_review='Fresh PNG rendering is generated separately. No claim of a completed human/model visual review.';
 if(auditFinal.duplicate_image_slide_groups.length)throw Error('Repeated image');if(auditFinal.issues.length)throw Error('Layout checks failed');
 const final=path.join(OUT,'AI_in_Pharmacodynamics_Revised_Teaching_Section.pptx');z.writeZip(final);const direct=path.join(ROOT,'pptx-package');z.extractAllTo(direct,true);fs.writeFileSync(path.join(OUT,'content_manifest.json'),JSON.stringify(spec,null,2));fs.writeFileSync(path.join(OUT,'audit.json'),JSON.stringify(auditFinal,null,2));
 // Only a handful of otherwise inaccessible source figures undergo OCR, once each, to locate panels.
 for(const key of ['pockets_fig3','antibiotics_fig2','wong_fig4',...(e3?['tnik_extended_9']:[])]){let f=fs.readdirSync(AS).find(n=>path.parse(n).name===key);if(!f)continue;try{const base=path.join(ROOT,'ocr',key);cp.execFileSync('tesseract',[path.join(AS,f),base,'--psm','11','tsv'],{timeout:60000,stdio:'ignore'});const lines=fs.readFileSync(base+'.tsv','utf8').split('\n').map(l=>l.split('\t')).filter(a=>a.length>=12&&+a[10]>35&&a[11].trim()).map(a=>({x:+a[6],y:+a[7],w:+a[8],h:+a[9],text:a[11]}));await publishText('ocr_'+key+'.json',lines);}catch(e){console.log('OCR_UNAVAILABLE',key,String(e));}}
 await publishText('audit.json',auditFinal);await publishText('content.json',spec);
 console.log('SAVED_REVISED_PPTX',final,JSON.stringify(auditFinal));
})().catch(e=>{console.error(e);process.exit(1)});
